name: PrisonCore
version: 1.0
main: me.prisoncore.Main
author: DUFC_Liam
description: The core for the prison server!

commands:
     announce:
         usage: /<command> <text>
         description: AYAYAYAYA
     clearchat:
         usage: /<command>
         description: AYAYAYAYA
     mutechat:
         usage: /<command>
         description: AYAYAYAYA