name: PrisonCore
version: 1.0
main: me.prisoncore.Main
author: DUFC_Liam
description: Fully Custom PrisonCore.

commands:
     announce:
         usage: /<command> <text>
         description: This will announce a message to everybody.
     clearchat:
         usage: /<command>
         description: This will clear chat for all non-staff.
     mutechat:
         usage: /<command>
         description: This will mute chat for all non-staff.
     vanish:
         usage: /<command>
         description: This will hide you from other players.
